#include <sys/types.h>
#include <unistd.h>
#include <stdio.h>
#include <dirent.h>
#include <errno.h>
#include <raylib.h>
#include <stdlib.h>
#include <sys/wait.h>
#include <signal.h>
#include <sys/stat.h> 
#include <fcntl.h>
#include <time.h>
#include <string.h> 
#include <pthread.h>
#include "raylib.h"
